"""add notifications

Revision ID: 2b60a5c15326
Revises: 51d47bc4dd59
Create Date: 2026-10-02 19:26:23.893113

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b60a5c15326"
down_revision: str | None = '51d47bc4dd59'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=10), server_default='NORMAL', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('ESTIMATE_READY', 'ESTIMATE_DECIDED', 'INVOICE_ISSUED', 'PAYMENT_RECEIVED', 'INVOICE_OVERDUE', 'REPAIR_ORDER_UPDATE', 'READY_FOR_PICKUP', 'APPOINTMENT_UPDATE', 'PART_REQUEST_SUBMITTED', 'PART_REQUEST_APPROVED', 'PURCHASE_ORDER_UPDATE', 'INVENTORY_LOW')", name='ck_notifications_type'),
    sa.CheckConstraint("priority IN ('NORMAL', 'HIGH')", name='ck_notifications_priority'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_unread', 'notifications', ['recipient_id', 'read_at'], unique=False)
    op.create_index('uq_notifications_dedupe', 'notifications', ['recipient_id', 'dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notifications_dedupe', table_name='notifications', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
