"""add parts and inventory

Revision ID: 3fb66728bf3e
Revises: 62627c5f7ab1
Create Date: 2026-10-02 14:57:24.199887

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fb66728bf3e"
down_revision: str | None = '62627c5f7ab1'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISCONTINUED')", name='ck_parts_status'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_parts_quantity_on_hand'),
    sa.CheckConstraint('reorder_level >= 0', name='ck_parts_reorder_level'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_parts_unit_cost'),
    sa.CheckConstraint('unit_price >= 0', name='ck_parts_unit_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_category'), 'parts', ['category'], unique=False)
    op.create_index(op.f('ix_parts_name'), 'parts', ['name'], unique=False)
    op.create_index(op.f('ix_parts_part_number'), 'parts', ['part_number'], unique=True)
    op.create_index(op.f('ix_parts_sku'), 'parts', ['sku'], unique=True)
    op.create_index(op.f('ix_parts_status'), 'parts', ['status'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('repair_order_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('from_location', sa.String(length=50), nullable=True),
    sa.Column('to_location', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('RECEIPT', 'ISSUE', 'RETURN', 'ADJUSTMENT', 'TRANSFER', 'SCRAP')", name='ck_inventory_transactions_type'),
    sa.CheckConstraint('quantity <> 0', name='ck_inventory_transactions_quantity'),
    sa.CheckConstraint('quantity_after >= 0', name='ck_inventory_transactions_after'),
    sa.CheckConstraint('quantity_before >= 0', name='ck_inventory_transactions_before'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_part_id'), 'inventory_transactions', ['part_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_performed_by_id'), 'inventory_transactions', ['performed_by_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_repair_order_id'), 'inventory_transactions', ['repair_order_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_repair_order_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_performed_by_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_part_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_parts_status'), table_name='parts')
    op.drop_index(op.f('ix_parts_sku'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_number'), table_name='parts')
    op.drop_index(op.f('ix_parts_name'), table_name='parts')
    op.drop_index(op.f('ix_parts_category'), table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###
