"""add suppliers and purchase orders

Revision ID: 5519e6a92a07
Revises: 3fb66728bf3e
Create Date: 2026-10-02 15:22:44.974907

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5519e6a92a07"
down_revision: str | None = '3fb66728bf3e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_suppliers_status'),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_suppliers_lead_time_days'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_account_number'), 'suppliers', ['account_number'], unique=False)
    op.create_index(op.f('ix_suppliers_created_by_id'), 'suppliers', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_is_preferred'), 'suppliers', ['is_preferred'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')", name='ck_purchase_orders_status'),
    sa.CheckConstraint('shipping_amount >= 0', name='ck_purchase_orders_shipping'),
    sa.CheckConstraint('subtotal >= 0', name='ck_purchase_orders_subtotal'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_purchase_orders_tax'),
    sa.CheckConstraint('total_amount >= 0', name='ck_purchase_orders_total'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_created_by_id'), 'purchase_orders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_expected_delivery_date'), 'purchase_orders', ['expected_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_order_date'), 'purchase_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_ordered > 0', name='ck_purchase_order_items_ordered'),
    sa.CheckConstraint('quantity_received <= quantity_ordered', name='ck_purchase_order_items_not_over'),
    sa.CheckConstraint('quantity_received >= 0', name='ck_purchase_order_items_received'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_purchase_order_items_unit_cost'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'part_id', name='uq_purchase_order_items_part')
    )
    op.create_index(op.f('ix_purchase_order_items_part_id'), 'purchase_order_items', ['part_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_part_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_order_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_expected_delivery_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_by_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_preferred'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_by_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_account_number'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
