"""add quality control

Revision ID: 62627c5f7ab1
Revises: c93f7e1a4b25
Create Date: 2026-10-02 08:37:43.654279

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62627c5f7ab1"
down_revision: str | None = 'c93f7e1a4b25'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_checks',
    sa.Column('repair_order_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'PASSED', 'FAILED')", name='ck_quality_checks_status'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_quality_checks_attempt_number'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_checks_inspector_id'), 'quality_checks', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_quality_checks_repair_order_id'), 'quality_checks', ['repair_order_id'], unique=False)
    op.create_index(op.f('ix_quality_checks_status'), 'quality_checks', ['status'], unique=False)
    op.create_table('qc_check_items',
    sa.Column('quality_check_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=30), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('auto_verified', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_type IN ('WORK_COMPLETED', 'PARTS_RECORDED', 'LABOR_RECORDED', 'PHOTOS_ATTACHED')", name='ck_qc_check_items_check_type'),
    sa.ForeignKeyConstraint(['quality_check_id'], ['quality_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_check_items_check_type'), 'qc_check_items', ['check_type'], unique=False)
    op.create_index(op.f('ix_qc_check_items_quality_check_id'), 'qc_check_items', ['quality_check_id'], unique=False)
    op.create_table('qc_photos',
    sa.Column('quality_check_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quality_check_id'], ['quality_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_photos_quality_check_id'), 'qc_photos', ['quality_check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_photos_quality_check_id'), table_name='qc_photos')
    op.drop_table('qc_photos')
    op.drop_index(op.f('ix_qc_check_items_quality_check_id'), table_name='qc_check_items')
    op.drop_index(op.f('ix_qc_check_items_check_type'), table_name='qc_check_items')
    op.drop_table('qc_check_items')
    op.drop_index(op.f('ix_quality_checks_status'), table_name='quality_checks')
    op.drop_index(op.f('ix_quality_checks_repair_order_id'), table_name='quality_checks')
    op.drop_index(op.f('ix_quality_checks_inspector_id'), table_name='quality_checks')
    op.drop_table('quality_checks')
    # ### end Alembic commands ###
