"""add invoices

Revision ID: 8ae203f2be1a
Revises: 5519e6a92a07
Create Date: 2026-10-02 18:05:58.163086

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ae203f2be1a"
down_revision: str | None = '5519e6a92a07'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('repair_order_id', sa.UUID(), nullable=False),
    sa.Column('estimate_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4, asdecimal=False), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID')", name='ck_invoices_status'),
    sa.CheckConstraint('amount_paid <= total', name='ck_invoices_not_overpaid'),
    sa.CheckConstraint('amount_paid >= 0', name='ck_invoices_amount_paid'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_invoices_discount'),
    sa.CheckConstraint('subtotal >= 0', name='ck_invoices_subtotal'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_invoices_tax_amount'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 1', name='ck_invoices_tax_rate'),
    sa.CheckConstraint('total >= 0', name='ck_invoices_total'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_order_id')
    )
    op.create_index(op.f('ix_invoices_created_by_id'), 'invoices', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_estimate_id'), 'invoices', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_vehicle_id'), 'invoices', ['vehicle_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('estimate_item_id', sa.UUID(), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('part_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(item_type = 'DISCOUNT' AND line_total <= 0) OR (item_type <> 'DISCOUNT' AND line_total >= 0)", name='ck_invoice_items_discount_sign'),
    sa.CheckConstraint("item_type IN ('LABOR', 'PART', 'SERVICE', 'FEE', 'DISCOUNT')", name='ck_invoice_items_type'),
    sa.CheckConstraint("source IN ('ESTIMATE', 'MANUAL')", name='ck_invoice_items_source'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_invoice_items_discount'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_items_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_items_unit_price'),
    sa.ForeignKeyConstraint(['estimate_item_id'], ['estimate_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_item_id', name='uq_invoice_items_estimate_item')
    )
    op.create_index(op.f('ix_invoice_items_estimate_item_id'), 'invoice_items', ['estimate_item_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_source'), 'invoice_items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_source'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_estimate_item_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_vehicle_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_estimate_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
