"""add appointments

Revision ID: c500515ba7a6
Revises: e0ff351c4e01
Create Date: 2026-09-20 11:55:39.862939

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c500515ba7a6"
down_revision: str | None = 'e0ff351c4e01'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('service_request_id', sa.UUID(), nullable=True),
    sa.Column('checkin_id', sa.UUID(), nullable=True),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('bay', sa.String(length=30), nullable=True),
    sa.Column('customer_concern', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name='ck_appointments_duration'),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
        "status IN ('REQUESTED', 'CONFIRMED', 'CHECKED_IN', 'IN_SERVICE', "
        "'COMPLETED', 'CANCELLED', 'NO_SHOW')",
        name='ck_appointments_status',
    )
    )
    op.create_index(op.f('ix_appointments_advisor_id'), 'appointments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_appointments_bay'), 'appointments', ['bay'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_start'), 'appointments', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_service_request_id'), 'appointments', ['service_request_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_status_start', 'appointments', ['status', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_technician_id'), 'appointments', ['technician_id'], unique=False)
    op.create_index(op.f('ix_appointments_vehicle_id'), 'appointments', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_vehicle_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_technician_id'), table_name='appointments')
    op.drop_index('ix_appointments_status_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_request_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_start'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_bay'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_advisor_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
