"""add labor and part requests

Revision ID: c93f7e1a4b25
Revises: b7e2a1c94d38
Create Date: 2026-10-01 21:53:52.223344

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c93f7e1a4b25"
down_revision: str | None = 'b7e2a1c94d38'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_records',
    sa.Column('repair_order_id', sa.UUID(), nullable=False),
    sa.Column('repair_task_id', sa.UUID(), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('billable_hours', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_hours >= 0', name='ck_labor_records_actual_hours'),
    sa.CheckConstraint('billable_hours >= 0', name='ck_labor_records_billable_hours'),
    sa.CheckConstraint('hourly_rate >= 0', name='ck_labor_records_hourly_rate'),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repair_task_id'], ['repair_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_records_performed_at'), 'labor_records', ['performed_at'], unique=False)
    op.create_index(op.f('ix_labor_records_repair_order_id'), 'labor_records', ['repair_order_id'], unique=False)
    op.create_index(op.f('ix_labor_records_repair_task_id'), 'labor_records', ['repair_task_id'], unique=False)
    op.create_index(op.f('ix_labor_records_technician_id'), 'labor_records', ['technician_id'], unique=False)
    op.create_table('part_requests',
    sa.Column('repair_order_id', sa.UUID(), nullable=False),
    sa.Column('repair_task_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'FULFILLED', 'CANCELLED')", name='ck_part_requests_status'),
    sa.CheckConstraint('quantity > 0', name='ck_part_requests_quantity'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repair_task_id'], ['repair_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_requests_repair_order_id'), 'part_requests', ['repair_order_id'], unique=False)
    op.create_index(op.f('ix_part_requests_repair_task_id'), 'part_requests', ['repair_task_id'], unique=False)
    op.create_index(op.f('ix_part_requests_requested_by_id'), 'part_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_part_requests_status'), 'part_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_requests_status'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_requested_by_id'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_repair_task_id'), table_name='part_requests')
    op.drop_index(op.f('ix_part_requests_repair_order_id'), table_name='part_requests')
    op.drop_table('part_requests')
    op.drop_index(op.f('ix_labor_records_technician_id'), table_name='labor_records')
    op.drop_index(op.f('ix_labor_records_repair_task_id'), table_name='labor_records')
    op.drop_index(op.f('ix_labor_records_repair_order_id'), table_name='labor_records')
    op.drop_index(op.f('ix_labor_records_performed_at'), table_name='labor_records')
    op.drop_table('labor_records')
    # ### end Alembic commands ###
