"""Customer documents: printable HTML for an estimate or an invoice.

A customer wants a copy of the paperwork, and wants it to be the same numbers the
shop holds. These renderers read the records and produce a self-contained HTML
document — no template engine, no PDF library, no network fonts — which the
browser can display, print, or save as PDF. Generating it server-side from the
record is deliberate: a document assembled in the browser from an API response is
one more place for the total to disagree with the invoice.

Every value is HTML-escaped. These documents are built from customer-supplied
text (descriptions, notes, names) and are downloaded as files, so an unescaped
apostrophe in a description would break the markup and a crafted one could
rewrite the page the moment it is opened.
"""

from __future__ import annotations

from html import escape

from app.core.config import settings
from app.estimates.models import Estimate
from app.invoices.models import Invoice

_STYLE = """
    body { font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif;
           color: #1a1a1a; margin: 40px; line-height: 1.5; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    h2 { font-size: 15px; margin: 28px 0 8px; text-transform: uppercase;
         letter-spacing: .06em; color: #666; }
    .meta { color: #555; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { text-align: left; padding: 8px 6px; border-bottom: 1px solid #e2e2e2;
             font-size: 14px; }
    th { font-weight: 600; color: #444; }
    .num { text-align: right; }
    .totals { margin-top: 16px; margin-left: auto; width: 320px; }
    .totals td { border: none; padding: 4px 6px; }
    .totals .grand { font-weight: 700; border-top: 2px solid #1a1a1a; }
    .notes { background: #f7f7f7; padding: 10px 12px; font-size: 14px;
             white-space: pre-wrap; }
    footer { margin-top: 40px; color: #888; font-size: 12px; }
"""


def _document(title: str, body: str) -> str:
    """Wrap a body in the shared document chrome."""
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        f"<title>{escape(title)}</title><style>{_STYLE}</style></head>"
        f"<body>{body}"
        f"<footer>Generated by {escape(settings.COMPANY_NAME)}. "
        "Please contact the shop if anything on this document looks wrong.</footer>"
        "</body></html>"
    )


def _rows(rows: list[str]) -> str:
    return "".join(rows)


def render_estimate_document(estimate: Estimate) -> tuple[str, str]:
    """Render an estimate. Returns ``(filename, html)``.

    A copy of what the customer was sent, not a live view: the document is built
    from the record as it stands now, which is why an issued invoice is frozen and
    an estimate's own lines are the only thing on it.
    """
    lines = []
    for item in estimate.items:
        lines.append(
            "<tr>"
            f"<td>{escape(item.description)}</td>"
            f"<td>{escape(item.item_type.title())}</td>"
            f"<td class='num'>{float(item.quantity or 0):g}</td>"
            f"<td class='num'>{float(item.unit_price or 0):,.2f}</td>"
            f"<td class='num'>{float(item.line_total or 0):,.2f}</td>"
            f"<td>{escape(item.status.title())}</td>"
            "</tr>"
        )

    body = (
        f"<h1>Estimate {escape(estimate.estimate_number)}</h1>"
        f"<p class='meta'>Status: {escape(estimate.status.replace('_', ' ').title())}"
        + (
            f" &middot; Valid until {escape(estimate.valid_until.isoformat())}"
            if estimate.valid_until
            else ""
        )
        + "</p>"
        "<h2>Items</h2><table><thead><tr><th>Description</th><th>Type</th>"
        "<th class='num'>Qty</th><th class='num'>Unit</th>"
        "<th class='num'>Amount</th><th>Decision</th></tr></thead>"
        f"<tbody>{_rows(lines)}</tbody></table>"
        "<h2>Totals</h2>"
        "<table class='totals'>"
        f"<tr><td>Subtotal</td><td class='num'>{float(estimate.subtotal):,.2f}</td></tr>"
        f"<tr><td>Discount</td><td class='num'>-{float(estimate.discount_amount):,.2f}</td></tr>"
        f"<tr><td>Tax</td><td class='num'>{float(estimate.tax_amount):,.2f}</td></tr>"
        f"<tr class='grand'><td>Total</td><td class='num'>{float(estimate.total):,.2f}</td></tr>"
        f"<tr><td>Approved so far</td><td class='num'>{estimate.approved_total:,.2f}</td></tr>"
        "</table>"
        + (
            f"<h2>Notes</h2><div class='notes'>{escape(estimate.notes)}</div>"
            if estimate.notes
            else ""
        )
    )
    return f"{estimate.estimate_number}.html", _document(
        f"Estimate {estimate.estimate_number}", body
    )


def render_invoice_document(invoice: Invoice) -> tuple[str, str]:
    """Render an invoice. Returns ``(filename, html)``."""
    lines = []
    for item in invoice.items:
        lines.append(
            "<tr>"
            f"<td>{escape(item.description)}</td>"
            f"<td>{escape(item.item_type.title())}</td>"
            f"<td class='num'>{float(item.quantity or 0):g}</td>"
            f"<td class='num'>{float(item.unit_price or 0):,.2f}</td>"
            f"<td class='num'>{float(item.line_total or 0):,.2f}</td>"
            "</tr>"
        )

    due = (
        f"<tr><td>Due date</td><td class='num'>{escape(invoice.due_date.isoformat())}</td></tr>"
        if invoice.due_date
        else ""
    )
    balance_row = (
        f"<tr class='grand'><td>Balance due</td>"
        f"<td class='num'>{invoice.balance:,.2f}</td></tr>"
        if invoice.has_balance
        else ""
    )

    body = (
        f"<h1>Invoice {escape(invoice.invoice_number)}</h1>"
        f"<p class='meta'>Status: {escape(invoice.status.replace('_', ' ').title())}</p>"
        "<h2>Items</h2><table><thead><tr><th>Description</th><th>Type</th>"
        "<th class='num'>Qty</th><th class='num'>Unit</th>"
        "<th class='num'>Amount</th></tr></thead>"
        f"<tbody>{_rows(lines)}</tbody></table>"
        "<h2>Totals</h2>"
        "<table class='totals'>"
        f"<tr><td>Invoice date</td><td class='num'>{escape(invoice.invoice_date.isoformat())}</td></tr>"
        f"{due}"
        f"<tr><td>Subtotal</td><td class='num'>{float(invoice.subtotal):,.2f}</td></tr>"
        f"<tr><td>Discount</td><td class='num'>-{float(invoice.discount_amount):,.2f}</td></tr>"
        f"<tr><td>Tax</td><td class='num'>{float(invoice.tax_amount):,.2f}</td></tr>"
        f"<tr class='grand'><td>Total</td><td class='num'>{float(invoice.total):,.2f}</td></tr>"
        f"<tr><td>Paid</td><td class='num'>{float(invoice.amount_paid):,.2f}</td></tr>"
        f"{balance_row}"
        "</table>"
        + (
            f"<h2>Notes</h2><div class='notes'>{escape(invoice.customer_notes or invoice.notes or '')}</div>"
            if (invoice.customer_notes or invoice.notes)
            else ""
        )
    )
    return f"{invoice.invoice_number}.html", _document(
        f"Invoice {invoice.invoice_number}", body
    )


__all__ = [
    "render_estimate_document",
    "render_invoice_document",
]
